### PR TITLE
Fix chrome custom tabs not used

### LINKED ISSUE #36: Chrome Custom Tabs is not used in some devices
An example device: Pixel 2 API 27

### PR DESCRIPTION
**Pull request by axolotl0212**
fix #36

# Screenshot

screenshot_20201103-131956_chrome

### CODE REVIEW

File: sdk/src/main/java/com/oursky/authgear/Authgear.kt [hunk 1]
```diff
@@ -268,16 +269,22 @@ constructor(
 
     /**
      * Open the specific path on the authgear server.
+     *
+     * @param activity Activity for starting Chrome custom tab activity.
+     * @param page Page in Authgear Web UI.
      */
-    fun openUrl(path: String) {
-        core.openUrl(path)
+    fun openUrl(activity: Activity, path: String) {
```
Comment (louischan-oursky) [inline sdk/src/main/java/com/oursky/authgear/Authgear.kt:276]: I wonder why we do not need to pass activity to authorize

Comment (axolotl0212) [reply sdk/src/main/java/com/oursky/authgear/Authgear.kt:276]: you mean the original implementation? This is because we can use `application` as context to start an activity, but this will require a new task (if not Android don't know where to put the activity). If we open an external browser than we can add `FLAG_ACTIVITY_NEW_TASK` and use `application.startActivity`

We can also do this for custom tab, but we will end up with two separate task (two item in recent app list) and I believe this is not wanted

Comment (louischan-oursky) [reply sdk/src/main/java/com/oursky/authgear/Authgear.kt:276]: I mean both authorize and openURL should have the same behavior. They do not create a new, separate task.

Comment (axolotl0212) [reply sdk/src/main/java/com/oursky/authgear/Authgear.kt:276]: I see, authorize will create an intent to start `OAuthActivity`, and the custom tab uses `OAuthActivity` as context

Comment (louischan-oursky) [reply sdk/src/main/java/com/oursky/authgear/Authgear.kt:276]: Oh, OAuthActivity is kind of magically. I am not sure if the authorization flow would still work if it is not only its own task stack.

Comment (louischan-oursky) [reply sdk/src/main/java/com/oursky/authgear/Authgear.kt:276]: Any updates on this issue?

Comment (axolotl0212) [reply sdk/src/main/java/com/oursky/authgear/Authgear.kt:276]: You want to create a separate activity for open url just like OAuthActivity for authorize button?

**Comment by axolotl0212** [comment]
@louischan-oursky rebased and pushed 1 more commit to add custom tab activity

**Comment by roxk** [comment]
@axolotl0212 While adding an activity works, I'd like to add some explanation. Theoretically, removing `NEW_TASK` flag in the `ACTION_VIEW` intent should work, as android has long has the ability to launch arbitrary activity (from different packages) in the same task, this is how apps can launch camera activity from other apps in the same task. In our case, it seems removing `NEW_TASK` wouldn't work as apparently most browser has set it's launch mode to `singleTask`, thus forcing the url to be opened in a new task. So adding an activity that uses custom tab should be the best solution here.

**Comment by axolotl0212** [comment]
> Theoretically, removing `NEW_TASK` flag in the `ACTION_VIEW` intent should work, as android has long has the ability to launch arbitrary activity (from different packages) in the same task, this is how apps can launch camera activity from other apps in the same task. 

When I tried to not include `NEW_TASK` flag, and use application as context to start custom tab, Android 10 device crashes and Android 8 devices start custom tab in new item in app list. Probably this is due to `launch mode = singleTask`?
